### ISSUE TITLE
Merge Conflict (object.cpp)

### ISSUE THREAD

**Issue by Nikonuk21** [ElunaLuaEngine/Eluna#175]
CONFLICT (content): Merge conflict in src/server/game/Entities/Object/Object.cpp
Latest TrinityCore : 3f29ce9e8f7c9c57eacf38493737b5a7bce39925

**Comment by Rochet2** [comment]
Do not report merge conflicts - they are not errors.
Its fine to report/remind if its been some time (over a week) since last merge.

Last merge with TC was 4 days ago.
Considering you got a merge error you are not using the preferred installation method.
Maybe you should read this (at top): https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/MERGING.md


Anyways, will merge next time on weekend most likely.
