### ISSUE TITLE
MoveTo makes creature stay at the given point

### ISSUE THREAD

**Issue by Phantoms123** [ElunaLuaEngine/Eluna#219]
Version: ElunaTrinityWotlk

Download date and compile: 15/3/2017

like the title says it seems to not work, heres is my script im working with,

its just the example creature with a couple of things added and nothing else,

im telling the creature to move to certain coords on the map at 50% hp or less and and telling it to talk when its moving as well.

seems to all work but the creature gets stuck when it gets to its location

and im thinking it might be a problem with the RemoveEvent part either that or something else could be broken or im possibly doing something wrong

[Eluna_Test_Script_2017.zip](https://github.com/ElunaLuaEngine/Eluna/files/846054/Eluna_Test_Script_2017.zip)

http://pastebin.com/U1Zx4X0e

**Comment by Foereaper** [comment]
Please upload scripts to eg. pastebin, zip and executable files aren't really considered safe and all that

**Comment by chovie23q** [comment]
http://pastebin.com/U1Zx4X0e

**Comment by Rochet2** [comment]
It seems that instead of timed events the problem is with the movement.
TC has changed so, that after using MoveTo (or MovePoint in C++) the NPC will stay at the given point.
To change this back to chasing the player or other victim target you should use `creature:MoveChase(creature:GetVictim())`

Here is an example of what to add to your script to make it work so, that when reaching the point, the NPC resumes chasing and attacking the victim target.
```lua
local MOVEMENT_TYPE_MOVE_TO = 8
local function OnWaypoint(event, creature, type, id)
    if type == MOVEMENT_TYPE_MOVE_TO and id == 1 then
        local target = creature:GetVictim()
        if target then
            creature:MoveChase(target)
        end
    end
end
RegisterCreatureEvent(npcId, 6, OnWaypoint)
```

**Comment by Rochet2** [comment]
Need to retest at some point - seems TC code may have changed the behavior later on back to what it used to be if this was a temporary bug.
