### ISSUE TITLE
Library path

### ISSUE THREAD

**Issue by raelik** [ElunaLuaEngine/Eluna#222]
I'm attempting to use LuaIRC with Eluna to build a Lua-based irc bridge, and I'm running into a slightly annoying issue (I've got lualib statically compiling luasocket, so that's not a problem).  LuaIRC has it's own sub-libraries that aren't intended to be loaded in isolation (the init.lua does that), and Eluna attempts to load all .lua and .ext files it comes across in lua_scripts.  Is there a way to define a lua library path that Eluna doesn't automatically search for files in?

**Comment by raelik** [comment]
So I made a tentative patch for this, works for my case: https://gist.github.com/raelik/8ac237419464879cc494ac165c08f3c6

**Comment by Rochet2** [comment]
> Is there a way to define a lua library path that Eluna doesn't automatically search for files in?

Hidden folders are not loaded.
Also any other folder, like lets say you have lua_scripts2 right next to lua_scripts folder is not loaded automatically. You can add it to the requirepath yourself in a lua script or you can use the "full path" in your requires, which is require("lua_scripts2/scriptfile")

The benefit with lua_scripts folder is though that you dont need to define the full path of the file for require, since the whole folder tree is added to the requirepath automatically.

I guess we could add this "special" folder. Though hiding a folder sort of has the same effect.
Hm, not sure.

**Comment by raelik** [comment]
The only issue with the entire tree being in the requirepath is that most libraries are written with the assumption that you have a system requirepath of `/usr/local/share/lua/<ver>/?.lua;/usr/local/share/lua/<ver>/?/init.lua`, so that any subdirectories are assumed to contain libraries within a given module (i.e. require "socket.http", which assumes the file is /usr/local/share/lua/<ver>/socket/http.lua)

The patch I wrote is basically recreating the default lua path, but within the server root.

**Comment by raelik** [comment]
I'll close this, as adding a .lib directory under lua_scripts and adding the appropriate package.path line at the top of my scripts that need it does the trick.
