### ISSUE TITLE
Nil Value Error (Solved)

### ISSUE THREAD

**Issue by warsongkiller** [ElunaLuaEngine/Eluna#237]
This is my code
function On_Gossip(pUnit, event, player)
    pUnit:GossipCreateMenu(1, player, 0)
    if player:HasQuest(23412) == true then
        pUnit:GossipMenuAddItem(4, "Summon Bronnend", 11, 0)
    end
    pUnit:GossipCreateMenu(4, "You don't have the quest", 3, 0)
    pUnit:GossipSendMenu(player)
end

function On_GossipSelect(pUnit, event, player, id, intid, code)
    if(intid == 11) then

    end
    if(intid == 3) then
        player:GossipComplete()
    end
end

RegisterUnitGossipEvent(7207, 1, "On_Gossip")
RegisterUnitGossipEvent(7207, 2, "On_GossipSelect")

And I get this error
Eluna Nova Lua Engine loaded.
Eluna Nova::Error loading `scripts\bronnend_quest.lua`.
        scripts\bronnend_quest.lua:19: attempt to call global 'RegisterUnitGossipEvent' (a nil value)
Eluna Nova::Loaded 3 Lua scripts
Reloaded Eluna Nova Engine

Please help me.

**Comment by Rochet2** [comment]
> attempt to call global 'RegisterUnitGossipEvent' (a nil value)

likely RegisterUnitGossipEvent should be RegisterCreatureGossipEvent.

> Eluna Nova Engine

Jesus .. Im fairly sure this was changed 3-4 years ago.
I would recommend using a newer core or compile the latest source or update your core or Eluna.

Closing because we dont support 4 years old code.
Create another issue if you have a newer version and still have some problems.
