### ISSUE TITLE
[Question] Compiling lua scripts

### ISSUE THREAD

**Issue by HKunogi** [ElunaLuaEngine/Eluna#266]
If i compile my lua scripts into .dll before loading then in the server, will i have any performance increases?
If i compile striping the debug info from the dll, will i have any performance increase compared to dlls with debug info embedded?

**Comment by Rochet2** [comment]
What kind of way would you use to add the script to a DLL?
I assume you don't talk about making a string in a DLL and having it contain the code or bytecode.
Why do you think the normal script would be inefficient, or what in it would be inefficient?

I don't know exactly how Lua represents data after it has loaded it. I would guess it is either bytecode which or some tree structures that are interpreted.
Any optimization of code would mean optimizing the bytecode or whatever the internal representation is.

In general, I don't think basically anything you do to the script has a real performance increase.
The scripts are loaded only once at the start of the server. Loading consists of compiling the code to bytecode and running the code.
After this step, all the code is in the internal memory of Lua in whatever representation it uses.

A real performance boost would come for example from using LuaJIT, which would generate directly executable and optimized native code instead of just interpreting whatever the user wrote.

**Comment by HKunogi** [comment]
Yes, i was only compiling them to bytecode before loading it. Thanks.

**Comment by Asandru** [comment]
There is not performance loss/increase
