### ISSUE TITLE
Player object ceases to exist

### ISSUE THREAD

**Issue by 55Honey** [ElunaLuaEngine/Eluna#351]
I'm using this code to assign a player object to a global variable:
```LUA
function testLogin(event, player)
    PlayerVariable = player
end
```

When i try to call the variable in an event one second later, the object is gone:
```LUA
PlayerVariable:SendBroadcastMessage("This worked.")
```
> lua_scripts/TestLogin.lua:8: calling 'SendBroadcastMessage' on bad self (Player expected, got pointer to nonexisting (invalidated) object (userdata). Check your code.)

How would i go about remembering the player which triggered the event?

**Comment by Rochet2** [comment]
Its possible that a player disconnects between two events. To prevent users from accessing objects that may have been freed, using objects between events is banned. Using a freed object can result in a crash or data corruption etc.

Instead of storing the object itself you can use store guids `guid = player:GetGUID()` and fetch the object by the guid with `player = map:GetWorldObject(guid)`.

Note that you need access to the map somehow and the player can be nil if he has logged out / disconnected when fetched.

**Comment by 55Honey** [comment]
```LUA
local PLAYER_EVENT_ON_LOGIN = 3    --  (event, player)

function testLogin(event, player)
    PlayerGUID = player:GetGUID()
    eventId = CreateLuaEvent(DelayedEvent, 1000, 1)
end

function DelayedEvent(eventId, delay, repeats)
    GetPlayerByGUID(PlayerGUID):SendBroadcastMessage("This worked.")
end

RegisterPlayerEvent(PLAYER_EVENT_ON_LOGIN, testLogin)
```

Works like a charm now. Thank you @Rochet2  :)
