### ISSUE TITLE
player:UnbindAllInstances freezes core

### ISSUE THREAD

**Issue by 55Honey** [ElunaLuaEngine/Eluna#353]
I am using Azerothcore 8bacb39d5334 2021-03-20

I've created a chat command event:
```
local PLAYER_EVENT_ON_COMMAND = 42
RegisterPlayerEvent(PLAYER_EVENT_ON_COMMAND, command)
```
Now this code leads to a freeze of the worldserver when using a command:
```
function command(event, player, command)
    player::UnbindAllInstances()
end
```
The core doesnt react anymore. Creatures outside a dungeon get stuck and turn towards the player but do neither move nor attack/cast spells.

**Comment by Rochet2** [comment]
A bug was recently fixed with unbinda all instances. Make sure you use latest versions of core & eluna.

Cannot reproduce with given instructions with
Windows 10
AC: 0bb4ab3e3ebe98381dedc4cb78fa2bfde8df48ad
modules/mod-eluna-lua-engine: 00320fcf50ca82247c8485211428c69f8368138e
modules/mod-eluna-lua-engine/LuaEngine: 8f5c4699b2531c408b615f55270541a7267c742b
```lua
local PLAYER_EVENT_ON_COMMAND = 42
function command(event, player, command)
  player:UnbindAllInstances()
  print("Lua: Unbound")
end
RegisterPlayerEvent(PLAYER_EVENT_ON_COMMAND, command)
```

**Comment by 55Honey** [comment]
Solved with updates. Thank you!
