### ISSUE TITLE
ShowMailBox is empty

### ISSUE THREAD

**Issue by ataraxyaffliction** [ElunaLuaEngine/Eluna#425]
Calling ShowMainBox opens an empty mail window. But if you open mail through a mailbox or GM command, and call ShowMailBox, then the mail will be displayed. 
I can’t understand what exactly is the problem, because the implementation of the request is essentially the same as that of GM command. Trinity core.

**Comment by Rochet2** [comment]
What is the guid you pass into ShowMailBox?
The guid is supposed to be a valid mailbox guid. Otherwise it will not work - except if you are a GM.
It seems that the NPC/player might also need to have npcflag 0x04000000 set.

I think this code nicely outlines the main restrictions: https://github.com/TrinityCore/TrinityCore/blob/53cc21b1b45e11ba9358df3281cfa2b021fb1ea0/src/server/game/Handlers/MailHandler.cpp#L36-L60

**Comment by ataraxyaffliction** [comment]
The Eluna documentation says that you need to pass the player's ID. If i try to pass the Mailbox object ID, nothing happens. Is it possible to open a game object interaction (for example, a mailbox or a guild bank)? Unfortunately, I didn't find anything in the documentation.

**Comment by ataraxyaffliction** [comment]
Yes, if you grant rbac permission 777 for the account, then everything works. As I understand, there are two options - grant permission, or remove the check from the core.

**Comment by Rochet2** [comment]
Is the mailbox close enough? The mailbox must be within interaction distance.

**Comment by ataraxyaffliction** [comment]
> Is the mailbox close enough? The mailbox must be within interaction distance.
Yeah, if mailbox close enough everything is working fine. But I wanted to use mail anywhere. I'll just add permission.
