### ISSUE TITLE
Safe env & Error handling

### ISSUE THREAD

**Issue by Rochet2** [ElunaLuaEngine/Eluna#98]
Use lua_cpcall to make C(++) to lua calls safer.
http://www.lua.org/pil/24.3.1.html

Try making a call stack when erroring for better error logs, possibly feature that one can turn off:
http://www.lua.org/manual/5.1/manual.html#lua_pcall
http://www.lua.org/pil/8.5.html
http://www.lua.org/pil/23.html
https://github.com/ignacio/StackTracePlus

Try using registery for the object table if needed
http://www.lua.org/manual/5.2/manual.html#4.5

**Comment by Patman64** [comment]
I'm going to close this issue since:

1. The `ExecuteCall` issue was fixed a long time ago.
2. Making `CHECKVAL` safe would require turning a Lua exception into a C++ exception (or some other wacky side effect) which would cause more issues than solve, so it's better if unprotected code just avoids calling `CHECKVAL` and does type checking/value copying with the Lua API directly.
